name: publish to npm and dockerhub

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node_version: ['14']

    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873

    steps:
      - run: echo ${{ job.services.verdaccio.ports['4873'] }}
      - run: echo "test\n123456\ntest@mail.com" | npm adduser --registry http://verdaccio:4873
      - run: echo "test\n123456\ntest@mail.com" | npm login --registry http://verdaccio:4873
      - run: npm whoami --registry http://verdaccio:4873
