name: publish to npm and dockerhub

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node_version: ['14']

    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
        
    steps:
      - uses: actions/checkout@v3
      - name: install expect
        run: |
          sleep 5
          apt-get update 
          apt-get -y install expect
          pwd
          ls
          chmod +x ./npm_registry_test.expect
      - name: exec expect
        run: |
          set timeout 10
          spawn npm adduser --registry http://verdaccio:4873
          expect "Username:"
          send "test\n"
          expect "Password:"
          send "123456\n"
          expect "Email: (this IS public)"
          send "test@mail.com\n"
          spawn npm login --registry http://verdaccio:4873
          expect "Username:"
          send "test\n"
          expect "Password:"
          send "123456\n"
          expect "Email: (this IS public)"
          send "test@mail.com\n"
        shell: expect {0}
      - name: test private npm registry
        run: |
          npm whoami --registry http://verdaccio:4873
      

