name: publish to npm and dockerhub

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node_version: ['14']

    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
        
    steps:
      - uses: actions/checkout@v3
      - run: sleep 5
      - run: apt-get install expect
      - run: chmod +x ./npm_registry_test.sh && ./npm_registry_test.sh
      - run: npm whoami --registry http://verdaccio:4873
      

