name: publish to npm and dockerhub

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node_version: ['14']

    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
        options: --health-cmd="curl --silent --fail localhost:4873/ || exit 1" --health-interval=10s --health-timeout=5s --health-retries=30

    steps:
      - run: echo "test\n123456\ntest@mail.com" | npm adduser --registry http://verdaccio:4873
      - run: echo "test\n123456\ntest@mail.com" | npm login --registry http://verdaccio:4873
      - run: npm whoami --registry http://verdaccio:4873
