name: publish to npm and dockerhub

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node_version: ['14']

    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
        
    steps:
      - uses: actions/checkout@v3
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - name: install expect
        run: |
          apt-get update 
          apt-get -y install expect
      - name: adduser and login test npm registry
        run: |
          set timeout 10
          spawn npm adduser --registry http://verdaccio:4873
          expect "Username:"
          send "test\n"
          expect "Password:"
          send "123456\n"
          expect "Email: (this IS public)"
          send "test@mail.com\n"
          spawn npm login --registry http://verdaccio:4873
          expect "Username:"
          send "test\n"
          expect "Password:"
          send "123456\n"
          expect "Email: (this IS public)"
          send "test@mail.com\n"
        shell: expect {0}
      - name: publish new version to test npm registry
        run: | 
          npm whoami --registry http://verdaccio:4873
          yarn version:alpha -y
          git config user.email "test@mail.com"
          git config user.name "test"
          git add .
          git commit -m "chore(versions): publish packages xxx"
          yarn release:force --registry http://verdaccio:4873
          npm view @nocobase/server --registry http://verdaccio:4873 | grep @nocobase/server@ 
          
      

