# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test_version

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node_version: ['14']

    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    steps:
      - 
        run: |
          echo '::echo::on'
          yarn create nocobase-app my-nocobase-app -d sqlite
          cd my-nocobase-app
          yarn install
          yarn nocobase install --lang=zh-CN
          yarn start > start.log &
          cat start.log
          sleep 5
          cat start.log
          sleep 5
          cat start.log
          sleep 5
          cat start.log
          sleep 10
          lang_data=$(curl http://localhost:13000/api/app:getLang)
          echo $lang_data
        shell: bash {0}
